version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DB_CONNECTION_STRING=Host=db;Database=SoftwareDirectory;Username=postgres;Password=Your_password123
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=SoftwareDirectory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Your_password123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    build:
      context: .
      target: build
    volumes:
      - .:/src
    working_dir: /src
    entrypoint: ["/bin/sh", "-c", "
      export PATH=\"$PATH:/root/.dotnet/tools\" &&
      echo 'Waiting for database...' &&
      sleep 5 &&
      echo 'Contents of /src:' &&
      ls -la /src &&
      echo 'Building project...' &&
      dotnet build &&
      echo 'Installing EF Core tools...' &&
      dotnet tool install --global dotnet-ef ||
      dotnet tool update --global dotnet-ef &&
      echo 'Running migrations...' &&
      /root/.dotnet/tools/dotnet-ef database update --verbose
      "]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Host=db;Database=SoftwareDirectory;Username=postgres;Password=Your_password123
    depends_on:
      db:
        condition: service_healthy
